#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opusfile
Version  : 0.10
Release  : 2
URL      : https://github.com/xiph/opusfile/archive/v0.10.tar.gz
Source0  : https://github.com/xiph/opusfile/archive/v0.10.tar.gz
Summary  : High-level Opus decoding library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: opusfile-lib
Requires: opusfile-doc
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(opus)

%description
# Opusfile
[![Travis Build Status](https://travis-ci.org/xiph/opusfile.svg?branch=master)](https://travis-ci.org/xiph/opusfile)
[![Jenkins Build Status](https://mf4.xiph.org/jenkins/buildStatus/icon?job=opusfile-autotools)](https://mf4.xiph.org/jenkins/view/opus/job/opusfile-autotools/)
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/xiph/opusfile?branch=master&svg=true)](https://ci.appveyor.com/project/rillian/opusfile)

%package dev
Summary: dev components for the opusfile package.
Group: Development
Requires: opusfile-lib
Provides: opusfile-devel

%description dev
dev components for the opusfile package.


%package doc
Summary: doc components for the opusfile package.
Group: Documentation

%description doc
doc components for the opusfile package.


%package lib
Summary: lib components for the opusfile package.
Group: Libraries

%description lib
lib components for the opusfile package.


%prep
%setup -q -n opusfile-0.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510689538
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1510689538
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/opus/opusfile.h
/usr/lib64/libopusfile.so
/usr/lib64/libopusurl.so
/usr/lib64/pkgconfig/opusfile.pc
/usr/lib64/pkgconfig/opusurl.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/opusfile/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopusfile.so.0
/usr/lib64/libopusfile.so.0.4.3
/usr/lib64/libopusurl.so.0
/usr/lib64/libopusurl.so.0.4.3
