#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v21
# autospec commit: 542402611043
#
Name     : opusfile
Version  : 0.12
Release  : 10
URL      : https://github.com/xiph/opusfile/archive/v0.12/opusfile-0.12.tar.gz
Source0  : https://github.com/xiph/opusfile/archive/v0.12/opusfile-0.12.tar.gz
Summary  : High-level Opus decoding library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: opusfile-lib = %{version}-%{release}
Requires: opusfile-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : file
BuildRequires : graphviz
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(opus)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Opusfile
[![GitLab Pipeline Status](https://gitlab.xiph.org/xiph/opusfile/badges/master/pipeline.svg)](https://gitlab.xiph.org/xiph/opusfile/commits/master)
[![Travis Build Status](https://travis-ci.org/xiph/opusfile.svg?branch=master)](https://travis-ci.org/xiph/opusfile)
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/xiph/opusfile?branch=master&svg=true)](https://ci.appveyor.com/project/rillian/opusfile)

%package dev
Summary: dev components for the opusfile package.
Group: Development
Requires: opusfile-lib = %{version}-%{release}
Provides: opusfile-devel = %{version}-%{release}
Requires: opusfile = %{version}-%{release}

%description dev
dev components for the opusfile package.


%package doc
Summary: doc components for the opusfile package.
Group: Documentation

%description doc
doc components for the opusfile package.


%package lib
Summary: lib components for the opusfile package.
Group: Libraries
Requires: opusfile-license = %{version}-%{release}

%description lib
lib components for the opusfile package.


%package license
Summary: license components for the opusfile package.
Group: Default

%description license
license components for the opusfile package.


%prep
%setup -q -n opusfile-0.12
cd %{_builddir}/opusfile-0.12
## copy_prepend content
# package_version file was missing in release 0.12
[[ -e "./package_version" ]] || echo PACKAGE_VERSION=%{version} > package_version
## copy_prepend end

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732133896
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1732133896
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opusfile
cp %{_builddir}/opusfile-%{version}/COPYING %{buildroot}/usr/share/package-licenses/opusfile/91dafd144e762845f6724a659114d9d6c2d5a7da || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/opus/opusfile.h
/usr/lib64/libopusfile.so
/usr/lib64/libopusurl.so
/usr/lib64/pkgconfig/opusfile.pc
/usr/lib64/pkgconfig/opusurl.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/opusfile/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopusfile.so.0
/usr/lib64/libopusfile.so.0.4.5
/usr/lib64/libopusurl.so.0
/usr/lib64/libopusurl.so.0.4.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opusfile/91dafd144e762845f6724a659114d9d6c2d5a7da
